# Write your MySQL query statement below
SELECT 
    PROJECT_ID,
    ROUND(AVG(EXPERIENCE_YEARS),2) AS average_years
FROM PROJECT P
INNER JOIN EMPLOYEE ON P.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
GROUP BY PROJECT_ID;